[build]
# Nixpacks configuration for Next.js application

# Use Node.js 18
[build.providers]
nodejs = "18"

[build.pkgs]
# Additional system packages if needed
# Example: pkg-config = "*"

[build.env]
# Build environment variables
NPM_CONFIG_PRODUCTION = "false"

[phases]
# Install phase - install dependencies
setup = "npm install --legacy-peer-deps"

# Build phase - build the Next.js application
build = "npm run build"

# Start phase - run production server
start = "npm run start"

[run]
# Runtime environment variables
PORT = "3002"
NODE_ENV = "production"

# Command to run the application
cmd = "npm run start"

# Exposed ports
ports = [3002]

# Health check configuration
[run.healthcheck]
enabled = true
cmd = "curl -f http://localhost:3002/ || exit 1"
interval = 30
timeout = 10
retries = 3
start_period = 40

# Resource limits (optional, can be overridden in Dokploy)
[run.resources]
memory = "512Mi"
cpu = "500m"
